Remove jsonpath from Parent POM dependencies. It strangely causes JSONPath `NoClassDefFoundError`s in Spring HATEOAS during runtime. Removing from Parent POM (but leaving in dspace-server-webapp) resolves those errors.